title: Marcel Cases
url: https://marcelcases.com
logo: "/images/montserrat.svg"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
permalink: "/projects/:title/"
markdown: kramdown
category_dir: ""
category_title_prefix: ""
author:
  fullname                  : Marcel Cases i Freixenet
  rss                       : false
  mail                      : m@rcel.xyz
  x                         : marcelcases
  github                    : marcelcases
  youtube                   : marcelcases
  telegram                  : marcelcases
  spotify                   : marcelcases
  linkedin                  : marcelcases
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
feed:
  path: feed/atom.xml
defaults:
  - scope:
      path: ""
    values:
      image: https://raw.githubusercontent.com/marcelcases/marcelcases.github.io/master/favicon/apple-icon-180x180.png
